---

- name: catalog dependencies
  notify: restart catalog
  package: name="{{item}}" state=latest
  with_items:
    - python-dev
    - libffi-dev
    - python-pip
    - git

- name: memcahed
  package: name=memcached state=latest

- name: catalog pip dependencies
  notify: "restart catalog"
  pip: name="{{item}}" state=latest
  with_items:
    - pip
    - pbr

- name: pip uwsgi
  notify: "restart catalog"
  pip: name=uwsgi state=latest
  when: catalog_deploy_with=="uwsgi"

- name: app catalog
  notify: "restart catalog"
  pip: name="{{catalog_pip}}"

- name: catalog uwsgi systemd file
  notify:
    - restart systemd
    - restart catalog
  template: src=templates/openstack-catalog.service dest=/etc/systemd/system/openstack-catalog.service
  when: (glare_deploy_with == "uwsgi") and
        (init == "systemd")

- name: catalog uwsgi systemd file
  notify:
    - restart catalog
  template: src=templates/openstack-catalog.conf dest=/etc/init/openstack-catalog.conf
  when: (glare_deploy_with == "uwsgi") and
        (init == "upstart")

- name: catalog config directory
  file: name=/etc/openstack-catalog state=directory

- name: openstack catalog config file
  notify: "restart catalog"
  template: src=templates/local_settings.py dest=/etc/openstack-catalog/local_settings.py
